name:                LuacheckConfigBuilder
version:             0.1.0.0
github:              "githubuser/LuacheckConfigBuilder"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/LuacheckConfigBuilder#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- directory
- filepath
# - bytestring
- containers
- text
- language-lua >= 0.10.0
- deepseq
- regex-pcre
# - regex-compat >= 0.95.1
# - data >=

# allow-newer: true

library:
  source-dirs: src

executables:
  LuacheckConfigBuilder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LuacheckConfigBuilder

tests:
  LuacheckConfigBuilder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LuacheckConfigBuilder
